name: Terraform

on:
  push:
    branches: [main]
    paths:
      - '**.tf'
      - 'html/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.tf'
      - 'html/**'

jobs:
  terraform:
    runs-on: [self-hosted, srv01, k3s]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
